### ISSUE TITLE
Support moya 7.0

### ISSUE THREAD

**Issue by ryanfitz** [DroidsOnRoids/Moya-JASON#2]
I ran into an issue on a project attempting to use the latest version of Moya. This library currently requires Moya 6.X.

**Comment by sunshinejr** [comment]
Hey @ryanfitz, thanks for the reminder! 🎉 

Was going to do it, but forgot in the meantime. I've released 0.3.0 version like a second ago, please try this one and let me know if there is anything we need to fix. 🐼

**Comment by ryanfitz** [comment]
@sunshinejr thanks for the super quick response! I was able to upgrade to moya 7 without issue. Great library btw

**Comment by sunshinejr** [comment]
No problem! My pleasure 🙇 And thanks for the kind words, appreciate it a lot!
